modify server.js and hooks for nodejitsu deploy

diff --git a/hooks/post-commit b/hooks/post-commit
--- a/hooks/post-commit
+++ b/hooks/post-commit
@@ -5,23 +5,7 @@ set -e
 set -o pipefail
 
 BRANCH=`git symbolic-ref HEAD --short`
-if [ "$BRANCH" != 'master' ] || [ -n "${SKIP+is_set}" ]; then
-  exit 0
+if [ "$BRANCH" = 'master' ]; then
+  VERSION=`node -e 'process.stdout.write(require("./package.json").version)'`
+  git tag "$VERSION" -m"version $VERSION" || echo 'WARNING: Tagging failed.'
 fi
-VERSION=`node -e 'process.stdout.write(require("./package.json").version)'`
-git tag "$VERSION" -m"version $VERSION" || echo 'WARNING: Tagging failed.'
-grunt clean
-git stash
-git checkout prebuilt
-git merge master
-grunt clean
-git rm -r dist
-grunt all:min
-npm shrinkwrap
-git add dist
-git add npm-shrinkwrap.json
-if [ ! `git diff-index --quiet --cached HEAD` ]; then
-  git commit -m'rebuild dist'
-fi
-git checkout "$BRANCH"
-git stash pop
